### ISSUE TITLE
npm run dev failed

### ISSUE THREAD

**Issue by danieldjakam** [rasengan-dev/rasenganjs#10] opened 2024-08-01 18:34 UTC
After initializing the rasengan project I want to do an npm run dev but I come across an error
![error](https://github.com/user-attachments/assets/47ca4900-cbf1-42c5-8b24-bdb348daca42)

**Comment by dilane3** [comment] 2024-08-01 20:52
Hi @danieldjakam, thanks for reporting your issue here.

Please can I have more information about your environment tools ? including:

- **OS version** (which version of Windows are you using ?)
- **Nodejs** and **NPM** versions

I will easily reproduce it on my side and directly come up with the issue.

Thanks

**Comment by danieldjakam** [comment] 2024-08-02 22:26
**Of course** @dilane3 

- I use Windows 10
- node v16.20.2 and npm v8.19.4

**Comment by dilane3** [comment] 2024-08-03 04:41
> **Of course** @dilane3
> 
> * I use Windows 10
> * node v16.20.2 and npm v8.19.4

I remark that you are using **Node v16.x**. The problem is coming here because according to the documentation website, Rasengan requires **Node v18.x** or later.

<img width="928" alt="Screenshot 2024-08-03 at 05 25 10" src="https://github.com/user-attachments/assets/45d9094f-2c11-492d-af00-f2d3725fedc5">

**Link**: [https://www.rasengan.dev/docs/getting-started/installation](https://www.rasengan.dev/docs/getting-started/installation)

You can upgrade your node version by downloading it here:
**Node website**: [https://nodejs.org/fr/download/package-manager](https://nodejs.org/fr/download/package-manager)

But if you have some projects which requires **Node 16.x**, don't worry you can use **NVM** to manage many versions of your node runtime and activate what you want to use at each time

**See how to use NVM**: [https://blog.logrocket.com/how-switch-node-js-versions-nvm/](https://blog.logrocket.com/how-switch-node-js-versions-nvm/)

If after that the problem is solved, please just mention that here so that we can close the issue.
If not, let me know.

Thanks.

**Comment by danieldjakam** [comment] 2024-08-04 16:01
**Problem solved thank you**
I hadn't noticed the problem

**Comment by dilane3** [comment] 2024-08-04 16:21
Okay super. 

Glad to know the problem has been solved on your side ✅

So let's close the issue 😊

**Closed by dilane3** 2024-08-04 16:21 UTC
